# Generated by Django 1.11.5 on 2017-09-15 06:43
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=100)),
                ('event', models.CharField(db_index=True, max_length=255)),
                ('eventDateTime', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bounceds',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('sender', models.EmailField(max_length=255)),
                ('recipient', models.EmailField(max_length=255)),
                ('body', models.TextField()),
                ('subject', models.CharField(max_length=256)),
                ('newsletter', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.TextField()),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('changeDateTime', models.DateTimeField(auto_now=True)),
                ('status_hash', models.CharField(blank=True, max_length=32, null=True,
                                                 verbose_name='Хеш статуса для безгеморройного индексирования')),
            ],
            options={
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Unsubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('newsletter', models.CharField(max_length=20)),
                ('unsubscribeDatetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Unsubscribers',
            },
        ),
    ]
