# Generated by Django 1.10.7 on 2017-09-18 08:38
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djnewsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='Домен')),
            ],
            options={
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='EmailServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_default_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='from:')),
                ('email_host', models.CharField(blank=True, max_length=100, null=True, verbose_name='хост')),
                ('email_port', models.IntegerField(blank=True, null=True, verbose_name='порт')),
                ('email_username',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='имя пользователя')),
                ('email_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='пароль')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='использовать SSL')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='использовать TLS')),
                ('email_fail_silently', models.BooleanField(default=False, verbose_name='Тихое подавление ошибок')),
                ('email_timeout', models.IntegerField(blank=True, null=True, verbose_name='тайм-аут')),
                ('email_ssl_certfile',
                 models.FileField(blank=True, max_length=500, null=True, upload_to='EmailServers/certfile/%Y/%m/%d',
                                  verbose_name='Сертификат')),
                ('email_ssl_keyfile',
                 models.FileField(blank=True, max_length=500, null=True, upload_to='EmailServers/keyfile/%Y/%m/%d',
                                  verbose_name='Файл ключа')),
                ('sendgrid_api_key',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='SENDGRID API KEY')),
                ('backend_name',
                 models.CharField(blank=True, help_text='Например: ebb.mail.EbbEmailBackend', max_length=1000,
                                  null=True, verbose_name='Путь к mail бэкэнду')),
                ('main', models.BooleanField(default=False, verbose_name='Основной сервер')),
                ('is_active', models.BooleanField(default=False, verbose_name='Сервер активен')),
                ('preferred_domains', models.ManyToManyField(blank=True, to='djnewsletter.Domains',
                                                             verbose_name='Предпочтительней для доменов')),
            ],
            options={
                'verbose_name_plural': 'EmailServers',
            },
        ),
    ]
