# Generated by Django 1.11.16 on 2019-03-04 16:57
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djnewsletter', '0002_domains_emailservers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailservers',
            old_name='sendgrid_api_key',
            new_name='api_key',
        ),
        migrations.AlterField(
            model_name='emailservers',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API KEY'),
        ),
    ]
