# Generated by Django 1.11.16 on 2019-03-25 09:19
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djnewsletter', '0005_auto_20190320_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailservers',
            name='api_from_email',
            field=models.CharField(blank=True, max_length=128, null=True,
                                   verbose_name='Email адрес для отправки через API'),
        ),
        migrations.AddField(
            model_name='emailservers',
            name='api_from_name',
            field=models.CharField(blank=True, max_length=128, null=True,
                                   verbose_name='Имя перед адресом для отправки через API'),
        ),
        migrations.AddField(
            model_name='emailservers',
            name='api_username',
            field=models.CharField(blank=True, max_length=128, null=True,
                                   verbose_name='Имя пользователя для авторизации в API'),
        ),
    ]
