# Generated by Django 1.11.22 on 2020-04-06 14:28
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djnewsletter', '0006_auto_20190325_0919'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emails',
            index=models.Index(fields=['-createDateTime'], name='djnewslette_createD_b40d62_idx'),
        ),
        migrations.AddIndex(
            model_name='emails',
            index=models.Index(fields=['-changeDateTime'], name='djnewslette_changeD_e5177d_idx'),
        ),
    ]
