# Generated by Django 2.2.12 on 2020-04-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('djnewsletter', '0007_auto_20200406_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailservers',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site', verbose_name='Сайт'),
        ),
    ]
